### ISSUE TITLE
Create basic story single view

### ISSUE THREAD

**Issue by spielhoelle** [DigitalCareerInstitute/marketing-website#81]
Display the image, write the alumniname, workposition etc. No styling, just creating Html elements and arrange them.
[Go here and click on Show more](https://dci.tmy.io/stories)

**Comment by shteyn** [comment]
@spielhoelle can you please provide a working example? Since the link is broken and there is an error
`TypeError: /home/dci/marketing-website/20181111135056/views/story.pug:4
    2| block content
    3|   .container.mt-5.text-left
  > 4|     h1.mr-3=story.title
    5|     p.mr-3=story.content
    6|     a.btn.btn-outline-primary(href='/admin/stories') Back
    7|   

Cannot read property 'title' of null
    at eval (eval at wrap (/home/dci/marketing-website/20181111135056/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:2224:63)
    at template (eval at wrap (/home/dci/marketing-website/20181111135056/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:2234:160)
    at Object.exports.renderFile (/home/dci/marketing-website/20181111135056/node_modules/pug/lib/index.js:427:38)
    at Object.exports.renderFile (/home/dci/marketing-website/20181111135056/node_modules/pug/lib/index.js:417:21)
    at View.exports.__express [as engine] (/home/dci/marketing-website/20181111135056/node_modules/pug/lib/index.js:464:11)
    at View.render (/home/dci/marketing-website/20181111135056/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/dci/marketing-website/20181111135056/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/dci/marketing-website/20181111135056/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/dci/marketing-website/20181111135056/node_modules/express/lib/response.js:1008:7)
    at /home/dci/marketing-website/20181111135056/controllers/StoriesController.js:23:9
    at /home/dci/marketing-website/20181111135056/node_modules/mongoose/lib/model.js:4187:16
    at model.Query.Query._completeOne (/home/dci/marketing-website/20181111135056/node_modules/mongoose/lib/query.js:1479:12)
    at Immediate.Query.base.findOne.call (/home/dci/marketing-website/20181111135056/node_modules/mongoose/lib/query.js:1535:10)
    at Immediate.<anonymous> (/home/dci/marketing-website/20181111135056/node_modules/mquery/lib/utils.js:119:16)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)`

**Comment by spielhoelle** [comment]
Lol - shit everytime when i reseed the production envirment it creates new story ids and the links are broken.
I update the description
